In [1]:
x, y = 0, 1
while x < 1000:
    print(x)
    x, y = y, x+y

0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


In [2]:
from astropy.table import Table, Column
import numpy as np

In [3]:
import numpy as np
print( np.diag(np.ones(4), 1) )

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [4]:
import numpy as np
A = np.arange(17)
A[1:14:2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [5]:
A[1:4]

array([1, 2, 3])

In [6]:
n=5
def funtest(n):
    s = (n,n)
    Y = zeros(s)
    for i in range(0,n-1):
        Y[i,i+1]=1          
    return Y

In [7]:
np.diagflat(np.ones(4,int),1)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [8]:
np.tril(np.triu(np.ones((5,5),int),1),1)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [9]:
np.triu(np.ones((5,5),int),1)

array([[0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [10]:
np.diag(np.ones(4),1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [11]:
a = np.linspace(0, 32, 100)
print(a)
for i in range(len(a)):
    a[i] = a[i]*a[i]
print(a)

[ 0.          0.32323232  0.64646465  0.96969697  1.29292929  1.61616162
  1.93939394  2.26262626  2.58585859  2.90909091  3.23232323  3.55555556
  3.87878788  4.2020202   4.52525253  4.84848485  5.17171717  5.49494949
  5.81818182  6.14141414  6.46464646  6.78787879  7.11111111  7.43434343
  7.75757576  8.08080808  8.4040404   8.72727273  9.05050505  9.37373737
  9.6969697  10.02020202 10.34343434 10.66666667 10.98989899 11.31313131
 11.63636364 11.95959596 12.28282828 12.60606061 12.92929293 13.25252525
 13.57575758 13.8989899  14.22222222 14.54545455 14.86868687 15.19191919
 15.51515152 15.83838384 16.16161616 16.48484848 16.80808081 17.13131313
 17.45454545 17.77777778 18.1010101  18.42424242 18.74747475 19.07070707
 19.39393939 19.71717172 20.04040404 20.36363636 20.68686869 21.01010101
 21.33333333 21.65656566 21.97979798 22.3030303  22.62626263 22.94949495
 23.27272727 23.5959596  23.91919192 24.24242424 24.56565657 24.88888889
 25.21212121 25.53535354 25.85858586 26.18181818 26

In [12]:
print(len(a))

100


In [13]:
n=16

In [14]:
a = np.linspace(1, 1, 16)
print(a)
for i in range(len(a)):
    a[i] = a[i]*a[i]
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
a = np.linspace(1, 1, n)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
for i in range(len(a)):
    a[i] = a[i]*a[i]
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
import pandas as pd

In [18]:
print(pd.DataFrame(a))

      0
0   1.0
1   1.0
2   1.0
3   1.0
4   1.0
5   1.0
6   1.0
7   1.0
8   1.0
9   1.0
10  1.0
11  1.0
12  1.0
13  1.0
14  1.0
15  1.0


In [19]:
import os
import numpy as np
import urllib.request

In [20]:
os.chdir("/Users/Roberto Benard Orci/Documents/Python Scripts")
os.getcwd()

'C:\\Users\\Roberto Benard Orci\\Documents\\Python Scripts'

In [21]:
Table1 = np.loadtxt(fname = "/Users/Roberto Benard Orci/Documents/Python Scripts/Table1.txt")

In [22]:
print(Table1)

[[ 1.00e+00  2.01e+02  5.92e+02  6.10e+01  9.00e+00 -8.40e-01]
 [ 2.00e+00  2.44e+02  4.01e+02  2.50e+01  4.00e+00  3.10e-01]
 [ 3.00e+00  4.70e+01  5.83e+02  3.80e+01  1.10e+01  6.40e-01]
 [ 4.00e+00  2.87e+02  4.02e+02  1.50e+01  7.00e+00 -2.70e-01]
 [ 5.00e+00  2.03e+02  4.95e+02  2.10e+01  5.00e+00 -3.30e-01]
 [ 6.00e+00  5.80e+01  1.73e+02  1.50e+01  9.00e+00  6.70e-01]
 [ 7.00e+00  2.10e+02  4.79e+02  2.70e+01  4.00e+00 -2.00e-02]
 [ 8.00e+00  2.02e+02  5.04e+02  1.40e+01  4.00e+00 -5.00e-02]
 [ 9.00e+00  1.98e+02  5.10e+02  3.00e+01  1.10e+01 -8.40e-01]
 [ 1.00e+01  1.58e+02  4.16e+02  1.60e+01  7.00e+00 -6.90e-01]
 [ 1.10e+01  1.65e+02  3.93e+02  1.40e+01  5.00e+00  3.00e-01]
 [ 1.20e+01  2.01e+02  4.42e+02  2.50e+01  5.00e+00 -4.60e-01]
 [ 1.30e+01  1.57e+02  3.17e+02  5.20e+01  5.00e+00 -3.00e-02]
 [ 1.40e+01  1.31e+02  3.11e+02  1.60e+01  6.00e+00  5.00e-01]
 [ 1.50e+01  1.66e+02  4.00e+02  3.40e+01  6.00e+00  7.30e-01]
 [ 1.60e+01  1.60e+02  3.37e+02  3.10e+01  5.00e+00 -5.

In [23]:
Table2 = np.loadtxt(fname = "/Users/Roberto Benard Orci/Documents/Python Scripts/Table2.txt")

In [24]:
print(Table2)

[[  5. 203. 495.  21.]
 [  6.  58. 173.  15.]
 [  7. 210. 479.  27.]
 [  8. 202. 504.  14.]
 [  9. 198. 510.  30.]
 [ 10. 158. 416.  16.]
 [ 11. 165. 393.  14.]
 [ 12. 201. 442.  25.]
 [ 13. 157. 317.  52.]
 [ 14. 131. 311.  16.]
 [ 15. 166. 400.  34.]
 [ 16. 160. 337.  31.]
 [ 17. 186. 423.  42.]
 [ 18. 125. 334.  26.]
 [ 19. 218. 533.  16.]
 [ 20. 146. 344.  22.]]


In [25]:
#Print first column
print(Table2[:,0])

#Print second row
print(Table2[1,:])

print(Table2[1,1])

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
[  6.  58. 173.  15.]
58.0


In [26]:
column_names = ['a', 'b', 'c','d']

Table2 = pd.DataFrame(Table2, columns=column_names)

In [27]:
print(Table2)

       a      b      c     d
0    5.0  203.0  495.0  21.0
1    6.0   58.0  173.0  15.0
2    7.0  210.0  479.0  27.0
3    8.0  202.0  504.0  14.0
4    9.0  198.0  510.0  30.0
5   10.0  158.0  416.0  16.0
6   11.0  165.0  393.0  14.0
7   12.0  201.0  442.0  25.0
8   13.0  157.0  317.0  52.0
9   14.0  131.0  311.0  16.0
10  15.0  166.0  400.0  34.0
11  16.0  160.0  337.0  31.0
12  17.0  186.0  423.0  42.0
13  18.0  125.0  334.0  26.0
14  19.0  218.0  533.0  16.0
15  20.0  146.0  344.0  22.0


In [28]:
Table2.index.name is None

True

In [29]:
print(Table2)

       a      b      c     d
0    5.0  203.0  495.0  21.0
1    6.0   58.0  173.0  15.0
2    7.0  210.0  479.0  27.0
3    8.0  202.0  504.0  14.0
4    9.0  198.0  510.0  30.0
5   10.0  158.0  416.0  16.0
6   11.0  165.0  393.0  14.0
7   12.0  201.0  442.0  25.0
8   13.0  157.0  317.0  52.0
9   14.0  131.0  311.0  16.0
10  15.0  166.0  400.0  34.0
11  16.0  160.0  337.0  31.0
12  17.0  186.0  423.0  42.0
13  18.0  125.0  334.0  26.0
14  19.0  218.0  533.0  16.0
15  20.0  146.0  344.0  22.0


In [30]:
Table2.idxmax()

a    15
b    14
c    14
d     8
dtype: int64

In [31]:
Table2['a'].idxmax()

15

In [32]:
(df[(Table2['a'] >= 5) & (df['a'] < 8)])

NameError: name 'df' is not defined

In [33]:
print(df.loc[(Table2['a'] >= 5) & (df['a'] < 8), 'b'])

NameError: name 'df' is not defined

In [34]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [35]:
np.linspace(0,1,10,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [36]:
np.arange(0.0, 1.0, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [45]:
y=1234
x=0.2
z=10


if  x < 1 :
    if y < 1 :
        if z < 50 :               
            print(1)
        elif z > 1000 :
            print(2)
        
        print(3)
    elif y > 1049 :
        print(4)
    print(5)    

4
5
